# .streamlit/secrets.example.toml
# -------------------------------------------------
# Dit bestand is een voorbeeld. 
# Zet hier géén echte wachtwoorden of API-keys in.
# -------------------------------------------------

[general]
# Bijv. de naam van je omgeving (development/staging/prod)
environment = "development"

[auth]
# API key voor externe diensten
API_TOKEN = "your_api_token_here"

[email]
# SMTP instellingen (optioneel als je ooit mails wilt versturen)
smtp_server = "smtp.yourmail.com"
smtp_port = 587
smtp_user = "user@example.com"
smtp_password = "your_password_here"
